// Enigma Alliance — Portfolio Data
window.PORTFOLIO_DATA = {
  owner: {
    name: "Aidan Dougan",
    title: "Game Designer & Creative Developer",
    tagline: "Systems-first. Logic-driven. Comfortable in Unreal, Unity, tabletop, and the space between.",
    email: "aidandougan24@gmail.com",
    phone: "+1 (314) 452-8267",
    resume: "Resume.pdf",
    about: "Senior at SCAD studying Interactive Design and Game Development. I'm drawn to how gameplay systems shape emotion, narrative, and player experience — whether that's building procedural environments, designing core mechanics, or bridging physical and digital interfaces. I love diving deep into how things work, and how they could work better.",
  },

  projects: [
    {
      id: "dough-or-die",
      num: "001",
      title: "Dough Or Die",
      role: "Product Owner",
      tagline: "Run a bakery. Fight mechs. Coming to Steam.",
      description: "You run a bakery by day, and an illegal underground mech arena by night — baking living bread machines that fight to promote your brand. Balance hands-on first-person mech combat with tactile, recipe-driven baking and business management.",
      contribution: "Served as Product Owner for Dough or Die, leading production while spearheading technical development and game design for our capstone team, guiding the project from initial concept through final product showcased at GDC, and into an upcoming Steam release.",
      tools: ["Unreal Engine 5", "Blueprint", "Systems Design", "Production Management"],
      status: "GDC → Steam",
      year: "2024–2025",
      team: "Open Peaks Studios",
      header: "DoughOrDie1.png",
      images: ["DoughOrDie2.png"],
      links: [
        { label: "Game Site", url: "https://openpeaksstudios.github.io", icon: "↗" },
        { label: "Watch Demo", url: "https://youtu.be/YD2L3g-tdLY", icon: "▶" },
      ],
      hasCaseStudy: true,
      caseStudy: {
        brief: "Capstone project — design and ship a commercially-viable game in one academic year. Constraint: team of 6, no prior shipped titles. Goal: GDC presentation + Steam release.",
        stats: [
          { k: "Timeline", v: "10 months" },
          { k: "Team Size", v: "6 people" },
          { k: "Platform", v: "PC → Steam" },
          { k: "Shown At", v: "GDC 2025" },
          { k: "Playtests", v: "12 sessions" },
          { k: "GDC Demos", v: "~200 players" },
        ],
        timeline: [
          { phase: "CONCEPT", date: "Sep 2024", detail: "Core loop ideation — bakery sim meets combat. Competitive analysis + paper prototyping." },
          { phase: "VERTICAL SLICE", date: "Nov 2024", detail: "First playable build. Baking mechanic + 1 arena. Internal playtest + iteration." },
          { phase: "ALPHA", date: "Jan 2025", detail: "All core systems functional. External playtest. Scope cuts based on feedback." },
          { phase: "BETA + GDC", date: "Mar 2025", detail: "Polish pass. GDC build locked. Demoed to 200+ industry professionals at booth 527." },
          { phase: "STEAM PREP", date: "Ongoing", detail: "Post-GDC polish, Steam store page, community build, and marketing assets." },
        ],
        systems: [
          { t: "Baking Loop", d: "Tactile, recipe-driven mechanic. Ingredient selection + timing determines bread unit stats and special abilities." },
          { t: "Mech Combat", d: "First-person arena combat. Bread units fight autonomously — their behavior is shaped by stats baked into them." },
          { t: "Business Layer", d: "Economy system tying revenue, upgrades, customer satisfaction, and brand reputation into a meta-loop." },
          { t: "Progression", d: "Unified meta-loop — unlock new recipes, arena slots, and upgrades by growing your bakery's notoriety." },
        ],
        iterations: [
          { v: "v0.1", note: "Paper prototype — baking was a turn-based card game. Felt disconnected from the combat layer." },
          { v: "v0.4", note: "Switched baking to real-time first-person interaction. Player engagement increased dramatically." },
          { v: "v0.7", note: "Removed PvP multiplayer — scope too large. Replaced with wave-based AI arena, which felt tighter." },
          { v: "v1.0", note: "GDC build. Core loop validated — 90% player retention across demo sessions at the booth." },
        ],
        technicalNotes: [
          { t: "Blueprint Architecture", d: "All gameplay logic in Blueprint. Modular actor-component system with clean separation of baking, combat, and economy layers." },
          { t: "Procedural Mech Behavior", d: "Behavior tree AI per bread unit. Stats from the baking loop influence node weights, producing emergent combat patterns." },
          { t: "Performance", d: "60fps target on mid-tier hardware. LOD system, occlusion culling, and async level streaming for arena transitions." },
        ],
        caseStudyPdf: "CaseStudy.pdf",
      },
    },
    {
      id: "clipped",
      num: "002",
      title: "Clipped",
      role: "Project Lead",
      tagline: "Stealth platformer. Art-heist ferret. Best Mechanic.",
      description: "Explore an elite art gallery and the worlds hidden inside its paintings. Use a magical clipping mask to cut elements from artworks, sneak past guards, crawl through vents, and assemble a defiant mixed-media masterpiece one snip at a time.",
      contribution: "Led a team of 26 peers as Project Lead for Clipped, directing the project from concept to completion in 48 hours during Global Game Jam 2026 (theme: Mask). Awarded Best Mechanic.",
      tools: ["Unreal Engine 5", "Blueprint", "Game Jam", "Team Leadership"],
      status: "Awarded: Best Mechanic",
      year: "2026",
      team: "Global Game Jam — SCAD",
      header: "Clipped1.png",
      images: [],
      links: [
        { label: "Jam Site", url: "https://globalgamejam.org/games/2026/clipped-9", icon: "↗" },
        { label: "Watch Trailer", url: "https://youtu.be/sikFj7aSr6I", icon: "▶" },
      ],
      hasCaseStudy: false,
    },
    {
      id: "crescendo",
      num: "003",
      title: "Crescendo",
      role: "Project Lead",
      tagline: "CV-powered physical therapy platform. 6\u00d7 Indigo Award winner.",
      description: "A computer vision-powered recovery platform that uses a standard laptop camera to guide, analyze, and connect at-home physical therapy with real-time clinical insight — improving accessibility, adherence, and long-term outcomes.",
      contribution: "Guided a seven-person student team from initial prompt to functional prototype in under 48 hours for SCAD's Hack-IX low-code hackathon. Aligned our vision with industry professionals and clinical standards. Awarded 1st place. Subsequently won 6 Indigo Design Awards including Silver in UX/Interface, and submitted for Red Dot 2026.",
      tools: ["Computer Vision", "TensorFlow", "Unreal Engine 5", "Python", "UX Design", "Healthcare"],
      status: "Hack-IX 1st Place",
      year: "2025",
      team: "SCAD — Hack-IX",
      awards: [
        { level: "Silver", body: "Indigo 2026", category: "Digital Design › UX, Interface & Navigation" },
        { level: "Bronze", body: "Indigo 2026", category: "Digital Design › Apps" },
        { level: "Bronze", body: "Indigo 2026", category: "Digital Design › Digital Tools & Utilities" },
        { level: "Bronze", body: "Indigo 2026", category: "Design for Social Change › Apps" },
        { level: "Bronze", body: "Indigo 2026", category: "Design for Social Change › Interaction Design" },
        { level: "HM",     body: "Indigo 2026", category: "Digital Design › Interactive Design" },
        { level: "Pending",body: "Red Dot 2026", category: "Submitted" },
      ],
      indigoBadge: "indigo-badge-silver.png",
      header: "crescendo-header.png",
      images: ["crescendo-arch.png", "crescendo-dashboard.png", "crescendo-checkin.png"],
      links: [
        { label: "Watch Demo", url: "https://youtu.be/59dwlT8-fOY", icon: "▶" },
      ],
      hasCaseStudy: false,
      galleryExtra: ["crescendo-ui-knee.png", "crescendo-milestones.png", "crescendo-profile.png", "crescendo-login.png", "crescendo-demo.png", "crescendo-ue-workout.png", "crescendo-team.png"],
    },
    {
      id: "snapshot",
      num: "004",
      title: "Snapshot",
      role: "Systems Designer",
      tagline: "1v1 shooter. The only weapon is your camera.",
      description: "A competitive 1v1 game where the only weapon is your camera — freeze enemies in time, frame the perfect shot, and outplay your opponent with precision and style.",
      contribution: "Led the design of Snapshot's core gameplay loop, focusing on the in-game camera as a tactical tool. Created prototype mechanics in UE5, balancing risk-reward around movement, line of sight, and player positioning.",
      tools: ["Unreal Engine 5", "Blueprint", "Multiplayer", "Systems Design"],
      status: "Prototype",
      year: "2025",
      team: "Solo / SCAD",
      header: "SnapshotHeeader.png",
      images: ["Snapshot1.png"],
      links: [
        { label: "Watch Trailer", url: "https://youtu.be/2aUiEHOOHAM", icon: "▶" },
      ],
      hasCaseStudy: false,
    },
    {
      id: "aether-912",
      num: "005",
      title: "Aether 912",
      role: "HMI Designer",
      tagline: "EV dashboard — Unity HMI + Arduino embedded systems.",
      description: "Designed onboard computing systems and human-machine interfaces for SCAD's electric vehicle prototype, bridging Unity visualization with Arduino-based physical controls and embedded systems.",
      contribution: "Led the design and prototyping of the Aether 912's digital interface systems. Created layout and logic for the onboard UI/UX, designed screen states and transitions, and mapped sensor inputs to human-readable feedback for the driver.",
      tools: ["Unity", "Arduino", "Embedded Systems", "HCI", "EV Prototyping"],
      status: "Complete",
      year: "2024",
      team: "SCAD — Electric Vehicle Team",
      header: "AetherHeeader.jpg",
      images: ["Aether1.jpg", "Aether2.jpg"],
      links: [],
      hasCaseStudy: false,
    },
    {
      id: "eternal-purge",
      num: "006",
      title: "Eternal Purge",
      role: "Project Lead",
      tagline: "Cooperative tabletop horror survival.",
      description: "A cooperative board game where time-traveling exorcists must survive a cursed keep, uncover a hidden relic, and hold back a creeping corruption — or be consumed by it.",
      contribution: "Co-developed the board game's core systems — corruption spread, tile discovery, sanity management, and relic recovery loops. Handled component layout, playtest feedback tracking, and win/loss state refinement.",
      tools: ["Tabletop Design", "Physical Prototyping", "Playtesting", "Systems Design"],
      status: "Complete",
      year: "2024",
      team: "SCAD",
      header: "EternalPurgeHeeader.webp",
      images: ["EternalPurge1.webp"],
      links: [
        { label: "Watch Trailer", url: "https://youtu.be/X21pJnOkyzw", icon: "▶" },
      ],
      hasCaseStudy: false,
    },
    {
      id: "between-lines",
      num: "007",
      title: "Between Lines",
      role: "Co-Developer (Mobile)",
      tagline: "Interrogate a sentient, broken typewriter.",
      description: "A narrative murder mystery where you interrogate a sentient typewriter — an unreliable, single-purpose AI that answers in cryptic word clusters you'll have to decode to uncover the truth.",
      contribution: "Developed the game's unique dialogue mechanic — where players interrogate a broken, sentient typewriter that can only reply in fragmented phrases. Designed the constrained output system, wrote branching clue responses, and prototyped the UI.",
      tools: ["Unity", "C#", "AI Systems", "Mobile Optimization", "Narrative Design"],
      status: "Complete",
      year: "2024",
      team: "SCAD",
      header: "BetweenLinesHeeader.png",
      images: [],
      links: [
        { label: "Watch Trailer", url: "https://youtu.be/dhydkVni1yU", icon: "▶" },
      ],
      hasCaseStudy: false,
    },
    {
      id: "room-generation",
      num: "008",
      title: "Room Generation",
      role: "System Designer",
      tagline: "Procedural dungeon generator in UE5 Blueprints.",
      description: "A procedural dungeon generator creating unique levels with balanced challenges and emergent gameplay possibilities, built entirely in UE5 Blueprints.",
      contribution: "Designed and implemented the full system in UE5 Blueprints — spawning logic, door-based snapping, overlap detection, and path extension. Built debugging tools to visualize snap points and placement flow.",
      tools: ["Unreal Engine 5", "Blueprint", "Procedural Generation", "Technical Design"],
      status: "Complete",
      year: "2024",
      team: "Solo / SCAD",
      header: "RoomGenHeeader.png",
      images: ["RoomGen2.png"],
      links: [
        { label: "Download Case Study", url: "CaseStudy.pdf", icon: "↓", download: true },
        { label: "Watch Trailer", url: "https://youtu.be/RATqNfp1jDo", icon: "▶" },
      ],
      hasCaseStudy: false,
    },
  ],

  professional: [
    {
      org: "Universal Creative",
      role: "Technical & Systems Design Lead",
      sub: "Advanced Technology Initiatives — SCADPro 2025",
      note: "Project details under NDA",
    },
    {
      org: "Mayo Clinic",
      role: "Project Manager",
      sub: "Innovation Alliances — SCADPro 2025",
      note: "Project details under NDA",
    },
  ],
};
